import { Kuliah } from "./types";

export const kuliahList: Kuliah[] = [
  {
    Organisation: "Masjid Annur",
    Prayer: "Subuh",
    Day: "Saturday",
    Details: "1st Week",
    Topic: "Indahnya Solat Berjemaah",
    Speaker: "Ustaz Md Zahil Md Yusof",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Subuh",
    Day: "Saturday",
    Details: "2nd Week",
    Topic: "Hadith 40 An-Nawawi",
    Speaker: "Ustaz Md Umaruddin Zainuddin",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Subuh",
    Day: "Saturday",
    Details: "3rd Week",
    Topic: "Adab Sulukil Murid",
    Speaker: "Ustaz Firda Abdul Wahid Md Hanif",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Subuh",
    Day: "Saturday",
    Details: "4th Week",
    Topic: "Ulum Quran",
    Speaker: "Ustaz Md Zuhdi Md Yusof",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Subuh",
    Day: "Saturday",
    Details: "5th Week",
    Topic: "Akhlaq Rasulullah S.A.W",
    Speaker: "Ustaz Nor Razak Bakar",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Subuh",
    Day: "Sunday",
    Details: "1st Week",
    Topic: "Safinatunnajah",
    Speaker: "Ustaz Ahmad Shamsuddin",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Subuh",
    Day: "Sunday",
    Details: "2nd Week",
    Topic: "Durratun Nasihin",
    Speaker: "Ustaz Husin Adam",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Subuh",
    Day: "Sunday",
    Details: "3rd Week",
    Topic: "Syamail Muhammadiyah",
    Speaker: "Ustaz Md Ali Rohani",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Subuh",
    Day: "Sunday",
    Details: "4th Week",
    Topic: "Kabair (Dosa-Dosa Besar)",
    Speaker: "Ustaz Md Khalid Rafi",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Subuh",
    Day: "Sunday",
    Details: "5th Week",
    Topic: "Ciri-Ciri Orang Yang Diredhai Allah",
    Speaker: "Ustaz Md Khair Rahmat",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Dhuha",
    Day: "Monday",
    Details: "9am - 10am",
    Topic: "An-Nujum Az-zahirah",
    Speaker: "Ustaz Leyaket Ali Omar",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Dhuha",
    Day: "Tuesday",
    Details: "9am - 10am",
    Topic: "Untaian Muriara Hadis",
    Speaker: "Ustaz Md Mamfizam Bakaram",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Dhuha",
    Day: "Wednesday",
    Details: "9am - 10am",
    Topic: "Pesanan Ilahi, Renungkanlah",
    Speaker: "Ustaz Md Bahrul-Ulum Buang",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Dhuha",
    Day: "Thursday",
    Details: "9am - 10am",
    Topic: "Tazkiyatun Nafs",
    Speaker: "Ustaz Md Zuhaili Md Yusof",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Dhuha",
    Day: "Monday",
    Details: "10.15m - 11.15am",
    Topic: "300 Hadis Bimbingan",
    Speaker: "Ustaz Firda Abdul Wahid Md Hanif",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Dhuha",
    Day: "Tuesday",
    Details: "10.15m - 11.15am",
    Topic: "Ensiklopedia Solat",
    Speaker: "Ustaz Md Umaruddin Zainuddin",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Dhuha",
    Day: "Wednesday",
    Details: "10.15m - 11.15am",
    Topic: "Tafsir Abrul Athir",
    Speaker: "Ustaz Md Kamal Mokhtar",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Dhuha",
    Day: "Thursday",
    Details: "10.15m - 11.15am",
    Topic: "Syarah Hikam",
    Speaker: "Ustaz Md Irwan Shah Sudiman",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Dhuha",
    Day: "Friday",
    Details: "8.30am - 9.30am",
    Topic: "Al-Wafi Syarah Hadith 40",
    Speaker: "Ustaz Qamarul Ariffin Kamarazaman",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Dhuha",
    Day: "Friday",
    Details: "9.30am - 10.30am",
    Topic: "Permata Ilmu Tauhid",
    Speaker: "Ustazah Nadia Hanim Abdul Rahman",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Zuhur",
    Day: "Monday",
    Details: "",
    Topic: "Tazkirah Umum",
    Speaker: "Ustaz Md Zuhaili Md Yusof",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Zuhur",
    Day: "Tuesday",
    Details: "",
    Topic: "Tazkirah Umum",
    Speaker: "Ustaz Md Nasir Abdul Rahim",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Zuhur",
    Day: "Wednesday",
    Details: "",
    Topic: "Tazkirah Umum",
    Speaker: "Ustaz Md Umaruddin Zainuddin",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Zuhur",
    Day: "Thursday",
    Details: "",
    Topic: "Tazkirah Umum",
    Speaker: "Ustaz Qamarul Ariffin Kamarazaman",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Maghrib",
    Day: "Monday",
    Details: "",
    Topic: "Ensiklopedia Solat",
    Speaker: "Ustaz Dr Syed Md Adib Termizi",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Maghrib",
    Day: "Tuesday",
    Details: "",
    Topic: "Tafsir Juz 'Amma",
    Speaker: "Ustaz Md Ali Atan",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Maghrib",
    Day: "Wednesday",
    Details: "",
    Topic: "Kisah-kisah Nabi dalam Al-Quran",
    Speaker: "Ustaz Adam Ismail",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Maghrib",
    Day: "Friday",
    Details: "",
    Topic: "Minhajul 'Abidin",
    Speaker: "Ustaz Md Kamal Yunos",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Maghrib",
    Day: "Saturday",
    Details: "",
    Topic: "Riyadhussolihin",
    Speaker: "Ustaz Ahmad Helmi Md Hasbi",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Maghrib",
    Day: "Sunday",
    Details: "",
    Topic: "Asbab Nuzulul Quran",
    Speaker: "Ustaz Maarof Mohd",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Isyak",
    Day: "Wednesday",
    Details: "",
    Topic: "Aqidah Ahlussunnah Wal Jamaah",
    Speaker: "Ustaz TM Fouzy TM Jumat",
  },
  {
    Organisation: "Masjid Annur",
    Prayer: "Isyak",
    Day: "Thursday",
    Details: "",
    Topic: "Kursus Haji & Umrah",
    Speaker: "Ustaz Musa Zulkifli",
  },
];
